# Generated by Django 4.2.6 on 2023-12-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='object',
            new_name='school_object',
        ),
        migrations.AlterField(
            model_name='estimation',
            name='number',
            field=models.CharField(max_length=20, verbose_name='Число'),
        ),
    ]
